# Generated by Django 5.2.13 on 2026-09-10 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assessment_option_a_assessment_option_b_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together={('user', 'course')},
        ),
    ]
