# Generated by Django 5.2.13 on 2026-09-09 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='option_a',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='assessment',
            name='option_b',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='assessment',
            name='option_c',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='assessment',
            name='option_d',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='answer',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.course'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
